"""allowing body date year and publication to be optional

Revision ID: 1b97fd7ed372
Revises: d62985211c99
Create Date: 2024-02-06 13:36:49.407019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b97fd7ed372'
down_revision: Union[str, None] = 'd62985211c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('article', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('article', 'publication',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'publication',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('article', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('article', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
