"""adding ground truth fields

Revision ID: eebcfac340d9
Revises: 0bb8ae05af04
Create Date: 2024-02-02 15:45:53.313566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebcfac340d9'
down_revision: Union[str, None] = '0bb8ae05af04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('ground_truth_headline_sentiment', sa.String(), nullable=True))
    op.add_column('article', sa.Column('ground_truth_body_subject', sa.String(), nullable=True))
    op.add_column('article', sa.Column('ground_truth_body_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'ground_truth_body_location')
    op.drop_column('article', 'ground_truth_body_subject')
    op.drop_column('article', 'ground_truth_headline_sentiment')
    # ### end Alembic commands ###
